### ISSUE TITLE
Missing parameters in m2c2kit survey module

### ISSUE THREAD

**Issue by ruoyush** [m2c2-project/m2c2kit#1]
Hello, I noticed that the survey module in m2c2 kit uses `nouislider` but it does not implement the "start" and "tooltips" parameters (tooltips are commented out in the code). Is there any specific reason for this? If not, may I submit a pull request to add these two parameters as follows?

in `nouislider-m2c2.ts`, add `start` as
```typescript
        {
          name: "start:number",
          category: "slider",
          default: 10,
        },
```
and edit
![Untitled](https://github.com/user-attachments/assets/fa91edf7-6ce3-4992-8979-e90c89d61798)

**Comment by syabiku** [comment]
Yes please do so.
